In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from matplotlib import style
from sklearn.model_selection import learning_curve
import statistics
import math
from sklearn.preprocessing import StandardScaler

In [2]:
# Importing from sklearn
from sklearn import datasets, linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import svm, metrics
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [3]:
run = pd.read_csv("sgemm_product.csv",index_col=False)
run["runavg (ms)"] = (run["Run1 (ms)"]+run["Run2 (ms)"]+run["Run3 (ms)"]+run["Run4 (ms)"])/4
run["log_run"] = np.where(run['runavg (ms)']>statistics.median(run["runavg (ms)"]), 1.0, 0.0)
run=run.drop(["runavg (ms)", "Run1 (ms)","Run2 (ms)","Run3 (ms)","Run4 (ms)"],axis=1)
run

MWG  NWG  KWG  MDIMC  NDIMC  MDIMA  NDIMB  KWI  VWM  VWN  STRM  STRN  \
0        16   16   16      8      8      8      8    2    1    1     0     0   
1        16   16   16      8      8      8      8    2    1    1     0     0   
2        16   16   16      8      8      8      8    2    1    1     0     0   
3        16   16   16      8      8      8      8    2    1    1     0     0   
4        16   16   16      8      8      8      8    2    1    1     0     1   
...     ...  ...  ...    ...    ...    ...    ...  ...  ...  ...   ...   ...   
241595  128  128   32     32     32     32     32    8    4    4     1     0   
241596  128  128   32     32     32     32     32    8    4    4     1     1   
241597  128  128   32     32     32     32     32    8    4    4     1     1   
241598  128  128   32     32     32     32     32    8    4    4     1     1   
241599  128  128   32     32     32     32     32    8    4    4     1     1   

        SA  SB  log_run  
0        0   0      1.0  
1        0   1      1.0  
2        1   0      1.0  
3        1   1      1.0  
4        0   0      1.0  
...     ..  ..      ...  
241595   1   1      0.0  
241596   0   0      0.0  
241597   0   1      0.0  
241598   1   0      0.0  
241599   1   1      0.0  

[241600 rows x 15 columns]

In [4]:
#Normalizing the data
def norm(dataset):
    scaler = StandardScaler()
    newd =scaler.fit_transform(dataset)
    return newd

In [5]:
X= run.iloc[:,:14]
Y=run.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=1)
X_train=norm(X_train)
X_test=norm(X_test)

In [6]:
from sklearn import metrics
model=svm.SVC()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred))

Accuracy Score:
0.9591197571743929


In [7]:
y_predt=model.predict(X_train)
print(metrics.accuracy_score(y_train,y_predt))

0.9614888836329234


In [8]:
# Creating a SVM classifier with C = 0.001, C =0.01 and C=0.1
modellogi1= svm.SVC(kernel = 'linear', C = 0.001)
modellogi2 = svm.SVC(kernel = 'linear', C = 0.01)
modellogi3 = svm.SVC(kernel = 'linear', C = 0.1)

In [9]:
modellogi1.fit(X_train,y_train)

SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [10]:
modellogi2.fit(X_train,y_train)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [11]:
modellogi3.fit(X_train,y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [12]:
y_predl1 = modellogi1.predict(X_test)
y_predl2 = modellogi2.predict(X_test)
y_predl3 = modellogi3.predict(X_test)

In [13]:
print(confusion_matrix(y_test,y_predl1))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predl1))

[[31313  4971]
 [ 7314 28882]]
Accuracy Score:
0.8305049668874173


In [14]:
print(confusion_matrix(y_test,y_predl2))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predl2))

[[31270  5014]
 [ 7273 28923]]
Accuracy Score:
0.8304773730684327


In [15]:
print(confusion_matrix(y_test,y_predl3))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predl3))

[[31264  5020]
 [ 7275 28921]]
Accuracy Score:
0.8303669977924945


In [16]:
modelpolyl1 = svm.SVC(kernel = 'poly', degree = 2, gamma = 'scale')
modelpolyl2 = svm.SVC(kernel = 'poly', degree = 4, gamma = 'scale')
modelpolyl3 = svm.SVC(kernel = 'poly', degree = 5, gamma = 'scale')

In [17]:
modelpolyl1.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [18]:
modelpolyl2.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=4, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
modelpolyl3.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [20]:
y_predpolyl1 = modelpolyl1.predict(X_test)
y_predpolyl2 = modelpolyl2.predict(X_test)
y_predpolyl3 = modelpolyl3.predict(X_test)

In [21]:
print(confusion_matrix(y_test,y_predpolyl1))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predpolyl1))

[[29819  6465]
 [12080 24116]]
Accuracy Score:
0.7441363134657837


In [22]:
print(confusion_matrix(y_test,y_predpolyl2))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predpolyl2))

[[35044  1240]
 [ 3111 33085]]
Accuracy Score:
0.939969646799117


In [23]:
print(confusion_matrix(y_test,y_predpolyl3))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predpolyl3))

[[35394   890]
 [ 2620 33576]]
Accuracy Score:
0.9515728476821192


In [24]:
modelrbfl1= svm.SVC(kernel = 'rbf', C = 0.001, gamma = 'scale')
modelrbfl2= svm.SVC(kernel = 'rbf', C = 0.01, gamma = 'scale')
modelrbfl3= svm.SVC(kernel = 'rbf', C = 0.1, gamma = 'scale')

In [25]:
modelrbfl1.fit(X_train,y_train)

SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
modelrbfl2.fit(X_train,y_train)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [27]:
modelrbfl3.fit(X_train,y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [28]:
y_predrbfl1 = modelrbfl1.predict(X_test)
y_predrbfl2 = modelrbfl2.predict(X_test)
y_predrbfl3 = modelrbfl3.predict(X_test)

In [29]:
print(confusion_matrix(y_test,y_predrbfl1))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predrbfl1))

[[32212  4072]
 [ 8710 27486]]
Accuracy Score:
0.8236479028697572


In [30]:
print(confusion_matrix(y_test,y_predrbfl2))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predrbfl2))

[[34136  2148]
 [ 5659 30537]]
Accuracy Score:
0.892287527593819


In [31]:
print(confusion_matrix(y_test,y_predrbfl3))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predrbfl3))

[[35303   981]
 [ 3522 32674]]
Accuracy Score:
0.9378725165562913


In [32]:
#Decision Trees
from sklearn.tree import DecisionTreeClassifier 

In [33]:
# Creating a Decision Tree clasifier object
dtcl = DecisionTreeClassifier()

dtcl = dtcl.fit(X_train,y_train)

In [34]:
y_preddtcl = dtcl.predict(X_test)

In [35]:
print(confusion_matrix(y_test,y_preddtcl))
print(classification_report(y_test,y_preddtcl))

[[35935   349]
 [  320 35876]]
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99     36284
         1.0       0.99      0.99      0.99     36196

    accuracy                           0.99     72480
   macro avg       0.99      0.99      0.99     72480
weighted avg       0.99      0.99      0.99     72480



In [36]:
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_preddtcl))

Accuracy Score:
0.9907698675496689


In [37]:
# Create a decision tree classifier object when depth is 5
dtcl1= DecisionTreeClassifier(criterion="entropy", max_depth=5)

dtcl1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [38]:
# Create a decision tree classifier object when depth is 10
dtcl2= DecisionTreeClassifier(criterion="entropy", max_depth=10)

dtcl2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [39]:
# Create a decision tree classifier object when depth is 15
dtcl3= DecisionTreeClassifier(criterion="entropy", max_depth=15)

dtcl3.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=15,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [40]:
y_preddtcl1 = dtcl1.predict(X_test)

y_preddtcl2 = dtcl2.predict(X_test)

y_preddtcl3 = dtcl3.predict(X_test)

In [41]:
print(confusion_matrix(y_test,y_preddtcl1))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_preddtcl1))

[[30447  5837]
 [ 7518 28678]]
Accuracy Score:
0.8157422737306843


In [42]:
print(confusion_matrix(y_test,y_preddtcl2))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_preddtcl2))

[[35409   875]
 [ 2303 33893]]
Accuracy Score:
0.9561534216335541


In [43]:
print(confusion_matrix(y_test,y_preddtcl3))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_preddtcl3))

[[35929   355]
 [  603 35593]]
Accuracy Score:
0.9867825607064018


In [44]:
#Importing libraries to perform boosting
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [45]:
# ADABOOST with Decision Trees when depth is 5
Adbl = AdaBoostClassifier(base_estimator = DecisionTreeClassifier(criterion='entropy', max_depth= 5), n_estimators = 400)

Adbl.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='entropy',
                                                         max_depth=5,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                          

In [46]:
modeladbl1 = AdaBoostClassifier(base_estimator = DecisionTreeClassifier(criterion='entropy', max_depth= 10), n_estimators = 400)

modeladbl1.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='entropy',
                                                         max_depth=10,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                         

In [47]:
modeladbl2 = AdaBoostClassifier(base_estimator = DecisionTreeClassifier(criterion='entropy', max_depth= 15), n_estimators = 400)

modeladbl2.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='entropy',
                                                         max_depth=15,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                         

In [51]:
y_predAdbl1 = Adbl.predict(X_test)
y_predadbl2 = modeladbl1.predict(X_test)
y_predadbl3 = modeladbl2.predict(X_test)

In [52]:
print(confusion_matrix(y_test,y_predAdbl1))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predAdbl1))

[[36007   277]
 [  345 35851]]
Accuracy Score:
0.9914183222958057


In [53]:
print(confusion_matrix(y_test,y_predadbl2))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predadbl2))

[[35986   298]
 [  317 35879]]
Accuracy Score:
0.9915149006622517


In [54]:
print(confusion_matrix(y_test,y_predadbl3))
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_predadbl3))

[[36027   257]
 [  308 35888]]
Accuracy Score:
0.9922047461368654
